### ISSUE TITLE
Przygotowanie dummy API

### ISSUE THREAD

**Issue by SuperbName** [BuczkowskiGabriel/AplikacjaKsi-kaKucharska#3]
Potrzebne puste działające API we Flasku, które będzie zwracało (co najmniej) dwa typy informacji:

- (/products) liste dostepnych produktow
- (/recommend, POST) rekomendacje (niech to na tę chwilę będzie 8 losowych przepisow z bazy, jeśli baza będzie gotowa lub zwrotke z dobra struktura ale z dowolnymi danymi)

**Comment by SuperbName** [comment]
Wrzucic (tymczasowo) na sztywno odpowiedzi do API, zeby frontendowcy mogli sobie sciagnac i odpalic API bez problemu

**Comment by SuperbName** [comment]
Jakies klopoty z tym?

**Comment by unununkwad** [comment]
Nie ma z tym problemu. Na /recommend aktualnie zwracamy 8 losowych przepisów wraz z ich składnikami z bazy. Frondend otrzymał wersję z odpowiedziami ustawionymi na sztywno bez konieczności łączenia się z bazą.

**Comment by SuperbName** [comment]
Ok. To wrzuccie kod na swoj branch (+ git push --set-upstream origin \<nazwa brancha\>) i zrobcie Pull Request w GitHub. Przejrze kod. Jesli potrzeba to beda poprawki i zamkne issue.

**Comment by SuperbName** [comment]
Nie widze tego nigdzie. Wrzuccie wszystko co dotyczy TEGO issue na osobny branch i zrobcie git push. Powtarzam, ze w tym issue chodzi o wrzucenie w **return** gotowych wartosci (z uzyciem dodatkowo **jsonify** i **dict**). Sprawdzcie tez, czy skrypt sie poprawnie uruchamia jako process. Jesli tak, to wrzuccie w **README.md**, jak go uruchamiacie jakiejs osobnej sekcji, np. _uruchamianie_ itp.

**Comment by SuperbName** [comment]
On hold

**Comment by SuperbName** [comment]
Zamykam. Musimy skupic sie na priorytetach.
