### ISSUE TITLE
Przygotowanie wstepnego frontendu

### ISSUE THREAD

**Issue by SuperbName** [BuczkowskiGabriel/AplikacjaKsi-kaKucharska#4]
Frontend ma odpytywac dwa endpointy i wyswietlac w miarę ładnie opakowaną listę produktów i w tabeli listę rekomendacji.

**Comment by SuperbName** [comment]
Skorzystać z przykładów z Internetu, by zrozumieć zasadę działania Reacta i komunikację między komponentami (np. aplikacja counter z https://reactjs.org/community/examples.html). Przygotować stronę wyświetlającą dwa komponenty
- jeden odpowiedzialny za wyswietlenie wszystkich produktow
- drugi za wyswietlenie wszystkich przepisow

Zanim uzyje sie fetch-a mozna wpisac potencjalne odpowiedzi jako zmienne w komponentach (np. klasowych).

**Comment by BuczkowskiGabriel** [comment]
Zrobiliśmy plik posts.json w którym wrzuciliśmy jsony które były wyświetlone we flasku, następnie te wyniki wrzuciliśmy do tabelek za pomocą reacta

**Comment by SuperbName** [comment]
Mozecie spushowac brancha, na ktorym pracujecie? (git push --set-upstream origin <nazwa-brancha>)

Tabelka - czyli cos juz wyswietla. Trzeba teraz sie zastanowic jak zrobic, by wyswietlalo
![ukw_front_tabela_excel](https://user-images.githubusercontent.com/75067789/101025628-23533200-3576-11eb-8a2a-2710798717fc.PNG)

Formularz - niech narazie bedzie zwykly (wielolinijkowy) multi select, ktory wyswietla w liscie wszystkie produkty. I jakis button, ktory chwilowo nic nie robi, zeby dobrze spozycjonowac elementy.
https://react-select.com/home

**Comment by BuczkowskiGabriel** [comment]
Witam zrobiliśmy tabelki, ale mamy problem z formularzem mamy zaimportowany plik posts.json do pliku Select.jsx(moduł formularza) ale nie umiemy zaimportować jsonów z pliku do formularza.
![Przechwytywanie1](https://user-images.githubusercontent.com/74784802/101091514-8d8cc680-35b8-11eb-8474-ea32e08d6a7e.PNG)
,

**Comment by BuczkowskiGabriel** [comment]
Witam zrobiliśmy wyszukiwanie za pomocą react select animation oraz przycisk teraz mam pytanię czy mamy edytować ten formularz jeszcze to znaczy czy mamy go inaczej umieścić bo też nie wiem jak zmniejszyć szerokość tego react search. 
![Przechwytywanie2](https://user-images.githubusercontent.com/74784802/101215719-98aa2a00-367e-11eb-8b82-ae4715b3a130.PNG)

**Comment by SuperbName** [comment]
Ok. Wyglada znacznie lepiej. Powinno się dać zmienic z poziomu CSS, tj. dodajesz selektor dot. search-a w **index.css** i zmieniasz **width** na inny. Selektor mozna znaledz robiac **inspect/zbadaj** z **devtools**.

**Comment by SuperbName** [comment]
Zamykam. Bedziemy kontynuowac w innym issue.
