### ISSUE TITLE
Frontend (formularz user'a) - wysylanie listy produktow do API

### ISSUE THREAD

**Issue by SuperbName** [BuczkowskiGabriel/AplikacjaKsi-kaKucharska#7]
Skupiamy sie tu tylko na formularzu usera.
- User ma miec mozliwosc wyboru wielu produktow, np. za pomoca __multiselect'a__, ktory byl wczesniej podany
- skladamy ten wybor do prostej listy, robimy z niej JSON'a
- __fetch__ z POST'em do API

**Comment by Somber21** [comment]
Mamy pytanie, o co dokładnie chodzi z tym fetchem?

**Comment by BuczkowskiGabriel** [comment]
![Przechwytywanie5](https://user-images.githubusercontent.com/74784802/102817944-f5bd1400-43d0-11eb-9ae1-5582cedbee8a.PNG)
Efekt formularza wraz z tabelami dodanymi do nich funkcję vertical-align: text-top;

**Comment by SuperbName** [comment]
@Somber21 Chodzi o funkcje JS, która odpytuje endpoint, (jesli potrzeba to wysyla i) pobiera dane. Tutaj trzeba zrobic POST, wiec wysylamy liste produktow. Robimy cos jak w przykladzie na stronie
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Uploading_JSON_data

```
fetch('https://localhost:5000/products', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify(data),
})
.then(response => response.json())
.catch((error) => {
  console.error('Error:', error);
});
```
POST z headerem, ze wysylamy JSON-a (zmienna `data`). Jak tylko `fetch` sie wykona wykona sie kod z `then` (tutaj zwrocona zostanie odpowiedz w JSON), a jesli `fetch` sie nie wykona poprawnie, to zwroci kod bledu, ktory jest obslugiwany w `catch` (tutaj wypisze do konsoli wiadomosc bledu.

@BuczkowskiGabriel Spoko. Jak to wyglada jak wyswietlone mamy dwa takie przepisy jeden pod drugim? Jesli jest duzo skladnikow to caly wiersz dla przepisu (ze skladnikami itd.) powinnismy jeszcze ostylowac `overflow`.
